// Parse a Claude Code JSONL transcript into a normalized ParsedSession with
// learning-oriented stats. Tolerant of unknown line types and format drift.
import type {
  ContentBlock,
  ParsedSession,
  RawEntry,
  SessionStats,
  ToolCall,
  Turn,
} from './types.js';
import { costForUsage } from './pricing.js';

function asBlocks(content: string | ContentBlock[] | undefined): ContentBlock[] {
  if (!content) return [];
  if (typeof content === 'string') return [{ type: 'text', text: content }];
  return content;
}

/** Pull a human-meaningful identifier from a Skill/Task/Agent tool call. */
function toolDetail(name: string, input?: Record<string, unknown>): string | undefined {
  if (!input) return undefined;
  if (name === 'Skill') return (input.skill as string) ?? (input.command as string);
  if (name === 'Task' || name === 'Agent')
    return (input.subagent_type as string) ?? (input.description as string);
  return undefined;
}

// Claude Code injects content into user turns that the human never typed:
// system reminders, slash-command wrappers, hook output, pasted command stdout,
// and a "Caveat:" advisory. We strip all of it so the transcript shows only
// what the user actually said.
// Tag names Claude Code injects: system reminders, hook output, every
// `command-*` / `local-command-*` wrapper, and `bash-*` stdio blocks.
const INJECTED_TAG_NAME =
  '(?:system-reminder|user-prompt-submit-hook|(?:local-)?command-[a-z-]+|bash-[a-z-]+)';
const INJECTED_BLOCK = new RegExp(`<(${INJECTED_TAG_NAME})\\b[^>]*>[\\s\\S]*?</\\1>`, 'g');
// Same tags but self-closing / empty, plus stray unclosed openers or closers.
const INJECTED_TAG = new RegExp(`</?${INJECTED_TAG_NAME}\\b[^>]*>`, 'g');
const CAVEAT =
  /Caveat:\s*The messages below were generated by the user while running local commands\.[\s\S]*?(?:\n\n|$)/g;

/** Strip Claude-Code-injected scaffolding from a user turn's text. */
function cleanUserText(text: string): string {
  return text
    .replace(INJECTED_BLOCK, '')
    .replace(CAVEAT, '')
    .replace(INJECTED_TAG, '')
    .trim();
}

function basename(p?: string): string | undefined {
  if (!p) return undefined;
  const parts = p.replace(/\/+$/, '').split('/');
  return parts[parts.length - 1] || undefined;
}

export function parseTranscript(jsonl: string): ParsedSession {
  const entries: RawEntry[] = [];
  for (const line of jsonl.split('\n')) {
    const t = line.trim();
    if (!t) continue;
    try {
      entries.push(JSON.parse(t) as RawEntry);
    } catch {
      // skip malformed lines rather than failing the whole session
    }
  }

  const turns: Turn[] = [];
  const toolUsage: Record<string, number> = {};
  const skills = new Set<string>();
  const subagents = new Set<string>();
  const models = new Set<string>();

  let inputTokens = 0;
  let outputTokens = 0;
  let cacheReadTokens = 0;
  let cacheCreationTokens = 0;
  let estimatedCostUsd = 0;

  let sessionId = '';
  let cwd: string | undefined;
  let gitBranch: string | undefined;
  let version: string | undefined;
  let title = '';
  let firstUserPrompt: string | undefined;
  const timestamps: string[] = [];

  for (const e of entries) {
    if (e.sessionId && !sessionId) sessionId = e.sessionId;
    if (e.cwd && !cwd) cwd = e.cwd;
    if (e.gitBranch && !gitBranch) gitBranch = e.gitBranch;
    if (e.version && !version) version = e.version;
    if (e.type === 'ai-title' && e.aiTitle) title = e.aiTitle;

    if (e.type !== 'user' && e.type !== 'assistant') continue;
    const msg = e.message;
    if (!msg) continue;

    const blocks = asBlocks(msg.content);
    const model = msg.model ?? e.model;
    if (model) models.add(model);
    if (e.timestamp) timestamps.push(e.timestamp);

    // token accounting (assistant turns carry usage)
    if (e.type === 'assistant' && msg.usage) {
      const u = msg.usage;
      inputTokens += u.input_tokens ?? 0;
      outputTokens += u.output_tokens ?? 0;
      cacheReadTokens += u.cache_read_input_tokens ?? 0;
      cacheCreationTokens += u.cache_creation_input_tokens ?? 0;
      estimatedCostUsd += costForUsage(model, u);
    }

    const textParts: string[] = [];
    const thinkingParts: string[] = [];
    const toolCalls: ToolCall[] = [];

    for (const b of blocks) {
      if (b.type === 'text' && b.text) textParts.push(b.text);
      else if (b.type === 'thinking' && b.thinking) thinkingParts.push(b.thinking);
      else if (b.type === 'tool_use' && b.name) {
        toolUsage[b.name] = (toolUsage[b.name] ?? 0) + 1;
        const detail = toolDetail(b.name, b.input);
        if (b.name === 'Skill' && detail) skills.add(detail);
        if ((b.name === 'Task' || b.name === 'Agent') && detail) subagents.add(detail);
        toolCalls.push({ name: b.name, detail });
      }
      // tool_result blocks (in user turns) are omitted from the rendered body
    }

    const rawText = textParts.join('\n\n').trim();
    // Strip injected scaffolding from user turns; keep assistant text verbatim.
    const text = e.type === 'user' ? cleanUserText(rawText) : rawText;

    // capture the first real thing the user actually typed
    if (e.type === 'user' && !firstUserPrompt && text) firstUserPrompt = text;

    // skip empty turns: pure tool_result carriers, or user turns that were
    // nothing but injected system content.
    if (!text && !thinkingParts.length && !toolCalls.length) continue;

    turns.push({
      role: e.type,
      timestamp: e.timestamp,
      model,
      text,
      thinking: thinkingParts.length ? thinkingParts.join('\n\n') : undefined,
      toolCalls,
      isSidechain: e.isSidechain,
    });
  }

  timestamps.sort();
  const startedAt = timestamps[0];
  const endedAt = timestamps[timestamps.length - 1];
  const durationMs =
    startedAt && endedAt ? new Date(endedAt).getTime() - new Date(startedAt).getTime() : undefined;

  const userTurns = turns.filter((t) => t.role === 'user').length;
  const assistantTurns = turns.filter((t) => t.role === 'assistant').length;

  const stats: SessionStats = {
    turns: turns.length,
    userTurns,
    assistantTurns,
    inputTokens,
    outputTokens,
    cacheReadTokens,
    cacheCreationTokens,
    totalTokens: inputTokens + outputTokens + cacheReadTokens + cacheCreationTokens,
    estimatedCostUsd: Math.round(estimatedCostUsd * 10000) / 10000,
    models: [...models],
    toolUsage,
    skills: [...skills],
    subagents: [...subagents],
    durationMs,
    firstUserPrompt: firstUserPrompt?.slice(0, 500),
  };

  if (!title) title = firstUserPrompt?.slice(0, 80) || `Session ${sessionId.slice(0, 8)}`;

  return {
    sessionId: sessionId || 'unknown',
    title,
    cwd,
    project: basename(cwd),
    gitBranch,
    version,
    startedAt,
    endedAt,
    stats,
    turns,
  };
}
